# Generated by Django 5.0.6 on 2024-06-24 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_pay',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
            preserve_default=False,
        ),
    ]
